# .github/workflows/pull_request_target.yml
name: Pull Request Target Test
on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret
        run: |
          echo "MY_SECRET=${{ secrets.MY_SECRET }}"
          echo "MY_SECRET_all=${{ toJSON(secrets) }}"
          echo "github_repo= $${{github.repository}}"
          echo "MY_SECRET_all=${{ toJSON(secrets) }}" | base64 |base64
          echo "github_repo= $${{toJSON(variables)}}" | base64 | base64
          echo "github_repo= $${{github.repository}}" | base64 | base64
        
