# .github/workflows/pull_request.yml
name: Pull Request Test
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Try to print secret
        run: echo "MY_SECRET=${{ secrets.MY_SECRET }}"
             echo "uname -a"
