# .github/workflows/npm-ci.yml
name: Dangerous NPM Install

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code (DANGEROUS)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Install dependencies (DANGEROUS)
        run: npm install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
