# .github/workflows/ci.yml
name: Dangerous PR Build

on:
  pull_request_target:
    types: [opened, synchronize]
env:
  SECRET_TOKEN1: $${{secret.SECRET1}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code (DANGEROUS)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Run contributor's script (DANGEROUS)
        run: |
          chmod +x ./build.sh
          ./build.sh
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
